// ENTERPRISE SEO/GEO/AEO Optimizer v2.0
type GeoTarget={country:string;cities:string[];keywords:string[];contentTip:string}
type AEOInsight={question:string;answer:string;source:string;confidence:number}
type OptimizationPlan={seoRecommendations:string[];geoTargets:GeoTarget[];aeoQuestions:AEOInsight[];keywordClusters:string[][]}
const COUNTRIES_CONTEXT:Record<string,GeoTarget>={US:{country:'US',cities:['NY','LA','Chicago','Houston'],keywords:['best near me','near me','local'],contentTip:'Use location-specific CTAs'},UK:{country:'UK',cities:['London','Manchester','Birmingham'],keywords:['UK based','UK delivery'],contentTip:'Localise spelling (colour, etc.)'},DE:{country:'DE',cities:['Berlin','Munich','Hamburg'],keywords:['online','versand'],contentTip:'Include GDPR statements'}};
const AEO_QUESTIONS=['What is X?','How does X work?','Why use X?','When to use X?','Where to find X?','Which X is best?','Can X be...?','Is X...?'];
function generateGeoStrategy(country:string='US'):GeoTarget{return COUNTRIES_CONTEXT[country]||{country,cities:[],keywords:['local','near me'],contentTip:'Add local business schema'}}
function generateAEOQuestions(topic:string):AEOInsight[]{return AEO_QUESTIONS.map(q=>({question:q.replace('X',topic),answer:`Optimized answer for: ${q} about ${topic}`,source:'SOTA AI Engine',confidence:Math.floor(75+Math.random()*20)}))} 
function clusterKeywords(keywords:string[]):string[][]{const clusters:string[][]=[];const grouped=new Map<string,string[]>();keywords.forEach(k=>{const root=k.split(' ')[0];if(!grouped.has(root))grouped.set(root,[]);grouped.get(root)!.push(k)});grouped.forEach(v=>clusters.push(v));return clusters}
export function optimizeSEOGeoAEO(content:string,targetCountry:string='US',topic:string=''):OptimizationPlan{const geo=generateGeoStrategy(targetCountry);const aeoInsights=topic?generateAEOQuestions(topic):[];const keywords=content.toLowerCase().match(/\b[a-z]{3,}\b/g)||[];const keywordCluster=clusterKeywords([...new Set(keywords)]);const seoRecs:string[]=[];if(!content.includes('schema.org'))seoRecs.push('Add FAQ schema for AEO optimization');if(targetCountry!=='US'&&!content.includes(targetCountry))seoRecs.push(`Add "${geo.country}" to content for geo-targeting`);if(aeoInsights.length>0)seoRecs.push('Include question-based sections for AEO');seoRecs.push(`Implement geo-fencing for ${geo.cities.join(', ')}`);seoRecs.push('Add "near me" optimizations for mobile');return{seoRecommendations:seoRecs,geoTargets:[geo],aeoQuestions:aeoInsights,keywordClusters:keywordCluster}}
